#!/bin/bash
#cd ./test
echo $(pwd)
echo "Setting permissions for files in git repo"

chmod 775 ./js
cd ./js
echo $(pwd)
find ./ -type d -exec chmod 775 {} \; &> /dev/null
find ./ -type f -exec chmod 664 {} \; &> /dev/null

chmod 775 ../cgi
cd ../cgi
echo $(pwd)
find ./ -type d -exec chmod 775 {} \; &> /dev/null
find ./ -type f -exec chmod 775 {} \; &> /dev/null

chmod 775 ../R
cd ../R
echo $(pwd)
find ./ -type d -exec chmod 775 {} \; &> /dev/null
find ./ -type f -exec chmod 664 {} \; &> /dev/null

chmod 775 ../db
cd ../db
echo $(pwd)
chmod 770 ./druggable
chmod 770 ./AuthAndSession
find ./ -name '*.sql' -exec chmod 660 {} \; &> /dev/null

chmod 775 ../help
cd ../help
echo $(pwd)
find ./ -type d -exec chmod 775 {} \; &> /dev/null
find ./ -type f -exec chmod 664 {} \; &> /dev/null

chmod 770 ../offline_scripts
cd ../offline_scripts
echo $(pwd)
find ./ -type f -exec chmod 775 {} \; &> /dev/null

chmod 775 ../druggable
cd ../druggable
echo $(pwd)
find ./ -type f -exec chmod 664 {} \; &> /dev/null

cd ..
echo $(pwd)
find ./ -maxdepth 1 -name '*.html' -exec chmod 664 {} \; &> /dev/null
find ./ -maxdepth 1 -name '*.css' -exec chmod 664 {} \; &> /dev/null
chmod 770 git-permissions
chmod 770 test-folder-git-permissions
